name: Protect Branches

on:
  push:
    branches:
      - develop
      - master

jobs:
  undo-push:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Check if push is a direct push (not from a pull request)
        run: |
          git fetch origin
          echo "commit_cnt=$(git log --oneline origin/develop.HEAD | wc -l)"
          
          echo '${{ toJson(github.event) }}' > event.json
          DISTINCT_FALSE_COUNT=$(jq '[.commits[] | select(.distinct == false)] | length' event.json)
          if [ "$DISTINCT_FALSE_COUNT" -eq 0 ]; then
            echo "This is a Direct Push."
          fi

#      - name: Check if push is a direct push (not from a pull request)
#        run: |
#          # Check if the push is part of a pull request
#          if [[ "$GITHUB_HEAD_REF" == "" ]]; then
#            echo "Direct push to develop or master is not allowed!"
#
#            # Get the previous commit SHA (before the push)
#            PREVIOUS_SHA=$(git log --pretty=format:"%H" -n 2 | tail -n 1)
#
#            # Force-push to reset the branch to the previous commit (undo the direct push)
#            git reset --hard $PREVIOUS_SHA
#            git push origin HEAD --force
#
#            exit 1
#          fi