name: Protect Branches

on:
  push:
    branches:
      - develop
      - master

jobs:
  undo-push:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Check if commit-sha file exists
        id: check_commit_sha
        run: |
          if [ -f "commit-sha.txt" ]; then
            echo "commit-sha.txt exists"
            echo "commit_sha_exists=true" >> $GITHUB_ENV
          else
            echo "commit-sha.txt does not exist"
            echo "commit_sha_exists=false" >> $GITHUB_ENV
          fi

      - name: Download commit-sha artifact
        if: env.commit_sha_exists == 'true'
        uses: actions/download-artifact@v3
        with:
          name: commit-sha

      - name: Check if commit SHA file exists
        id: check_file
        run: |
          if [ -f last_commit_sha.txt ]; then
            echo "File exists."
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "File does not exist."
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      - name: Compare and count new commits
        if: env.file_exists == 'true'  # 파일이 존재하는 경우에만 실행
        run: |
          LAST_COMMIT_SHA=$(cat last_commit_sha.txt)
          echo "Previous commit SHA: $LAST_COMMIT_SHA"

      - name: Check if push is a direct push (not from a pull request)
        run: |
          echo '${{ toJson(github.event) }}' > event.json
          DISTINCT_FALSE_COUNT=$(jq '[.commits[] | select(.distinct == false)] | length' event.json)
          if [ "$DISTINCT_FALSE_COUNT" -eq 0 ]; then
            echo "This is a Direct Push."
          fi

      - name: Save last commit SHA
        run: |
          echo "LAST_COMMIT_SHA=$(git rev-parse HEAD)" > last_commit_sha.txt

      - name: Upload commit SHA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: commit-sha
          path: last_commit_sha.txt

#      - name: Check if push is a direct push (not from a pull request)
#        run: |
#          # Check if the push is part of a pull request
#          if [[ "$GITHUB_HEAD_REF" == "" ]]; then
#            echo "Direct push to develop or master is not allowed!"
#
#            # Get the previous commit SHA (before the push)
#            PREVIOUS_SHA=$(git log --pretty=format:"%H" -n 2 | tail -n 1)
#
#            # Force-push to reset the branch to the previous commit (undo the direct push)
#            git reset --hard $PREVIOUS_SHA
#            git push origin HEAD --force
#
#            exit 1
#          fi